global using SocialMedia.Application.Common.Interfaces;
global using SocialMedia.Application.Users.Command;
global using SocialMedia.WebUI.Services;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using MediatR;
global using SocialMedia.Application;
global using SocialMedia.Infrastucture;